# Homologacao (staging) profile - PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/security}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Usar Flyway para schema; desabilitar DDL auto
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.jpa.show-sql=false

# H2 console disabled in hml
spring.h2.console.enabled=false
